<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CarModel;

class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $carModels = [
            ['car_brand_id' => 1, 'name' => '4-Runner', 'slug' => '4-runner'],
            ['car_brand_id' => 1, 'name' => 'Auris', 'slug' => 'auris'],
            ['car_brand_id' => 1, 'name' => 'Avalon', 'slug' => 'avalon'],
            ['car_brand_id' => 1, 'name' => 'Avensis', 'slug' => 'avensis'],
            ['car_brand_id' => 1, 'name' => 'Avensis Verso', 'slug' => 'avensis-verso'],
            ['car_brand_id' => 1, 'name' => 'Aygo', 'slug' => 'aygo'],
            ['car_brand_id' => 1, 'name' => 'Aygo X', 'slug' => 'aygo-x'],
            ['car_brand_id' => 1, 'name' => 'bZ4X', 'slug' => 'bz4x'],
            ['car_brand_id' => 1, 'name' => 'C-HR', 'slug' => 'c-hr'],
            ['car_brand_id' => 1, 'name' => 'Camry', 'slug' => 'camry'],
            ['car_brand_id' => 1, 'name' => 'Camry Solara', 'slug' => 'camry-solara'],
            ['car_brand_id' => 1, 'name' => 'Carina', 'slug' => 'carina'],
            ['car_brand_id' => 1, 'name' => 'Celica', 'slug' => 'celica'],
            ['car_brand_id' => 1, 'name' => 'Corolla', 'slug' => 'corolla'],
            ['car_brand_id' => 1, 'name' => 'Corolla Cross', 'slug' => 'corolla-cross'],
            ['car_brand_id' => 1, 'name' => 'Corolla Verso', 'slug' => 'corolla-verso'],
            ['car_brand_id' => 1, 'name' => 'Cressida', 'slug' => 'cressida'],
            ['car_brand_id' => 1, 'name' => 'Crown', 'slug' => 'crown'],
            ['car_brand_id' => 1, 'name' => 'Dyna', 'slug' => 'dyna'],
            ['car_brand_id' => 1, 'name' => 'FJ', 'slug' => 'fj'],
            ['car_brand_id' => 1, 'name' => 'GR86', 'slug' => 'gr86'],
            ['car_brand_id' => 1, 'name' => 'Grand Highlander', 'slug' => 'grand-highlander'],
            ['car_brand_id' => 1, 'name' => 'GT86', 'slug' => 'gt86'],
            ['car_brand_id' => 1, 'name' => 'Hiace', 'slug' => 'hiace'],
            ['car_brand_id' => 1, 'name' => 'Highlander', 'slug' => 'highlander'],
            ['car_brand_id' => 1, 'name' => 'Hilux', 'slug' => 'hilux'],
            ['car_brand_id' => 1, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 1, 'name' => 'iQ', 'slug' => 'iq'],
            ['car_brand_id' => 1, 'name' => 'Land Cruiser', 'slug' => 'land-cruiser'],
            ['car_brand_id' => 1, 'name' => 'Lite-Ace', 'slug' => 'lite-ace'],
            ['car_brand_id' => 1, 'name' => 'Matrix', 'slug' => 'matrix'],
            ['car_brand_id' => 1, 'name' => 'Mirai', 'slug' => 'mirai'],
            ['car_brand_id' => 1, 'name' => 'MR2', 'slug' => 'mr2'],
            ['car_brand_id' => 1, 'name' => 'Paseo', 'slug' => 'paseo'],
            ['car_brand_id' => 1, 'name' => 'Picnic', 'slug' => 'picnic'],
            ['car_brand_id' => 1, 'name' => 'Previa', 'slug' => 'previa'],
            ['car_brand_id' => 1, 'name' => 'Prius', 'slug' => 'prius'],
            ['car_brand_id' => 1, 'name' => 'Prius+', 'slug' => 'prius_plus'],
            ['car_brand_id' => 1, 'name' => 'ProAce', 'slug' => 'proace'],
            ['car_brand_id' => 1, 'name' => 'Proace City', 'slug' => 'proace-city'],
            ['car_brand_id' => 1, 'name' => 'Proace City Verso', 'slug' => 'proace-city-verso'],
            ['car_brand_id' => 1, 'name' => 'Proace Verso', 'slug' => 'proace-verso'],
            ['car_brand_id' => 1, 'name' => 'RAV4', 'slug' => 'rav4'],
            ['car_brand_id' => 1, 'name' => 'Sequoia', 'slug' => 'sequoia'],
            ['car_brand_id' => 1, 'name' => 'Sienna', 'slug' => 'sienna'],
            ['car_brand_id' => 1, 'name' => 'Starlet', 'slug' => 'starlet'],
            ['car_brand_id' => 1, 'name' => 'Supra', 'slug' => 'supra'],
            ['car_brand_id' => 1, 'name' => 'Tacoma', 'slug' => 'tacoma'],
            ['car_brand_id' => 1, 'name' => 'Tercel', 'slug' => 'tercel'],
            ['car_brand_id' => 1, 'name' => 'Tundra', 'slug' => 'tundra'],
            ['car_brand_id' => 1, 'name' => 'Urban Cruiser', 'slug' => 'urban-cruiser'],
            ['car_brand_id' => 1, 'name' => 'Venza', 'slug' => 'venza'],
            ['car_brand_id' => 1, 'name' => 'Verso', 'slug' => 'verso'],
            ['car_brand_id' => 1, 'name' => 'Verso S', 'slug' => 'verso-s'],
            ['car_brand_id' => 1, 'name' => 'Yaris', 'slug' => 'yaris'],
            ['car_brand_id' => 1, 'name' => 'Yaris Cross', 'slug' => 'yaris-cross'],
            ['car_brand_id' => 1, 'name' => 'Yaris Verso', 'slug' => 'yaris-verso'],
            ['car_brand_id' => 2, 'name' => '181', 'slug' => '181'],
            ['car_brand_id' => 2, 'name' => 'Amarok', 'slug' => 'amarok'],
            ['car_brand_id' => 2, 'name' => 'Arteon', 'slug' => 'arteon'],
            ['car_brand_id' => 2, 'name' => 'Atlas', 'slug' => 'atlas'],
            ['car_brand_id' => 2, 'name' => 'Beetle', 'slug' => 'beetle'],
            ['car_brand_id' => 2, 'name' => 'Bora', 'slug' => 'bora'],
            ['car_brand_id' => 2, 'name' => 'Buggy', 'slug' => 'buggy'],
            ['car_brand_id' => 2, 'name' => 'Caddy', 'slug' => 'caddy'],
            ['car_brand_id' => 2, 'name' => 'California', 'slug' => 'california'],
            ['car_brand_id' => 2, 'name' => 'Caravelle', 'slug' => 'caravelle'],
            ['car_brand_id' => 2, 'name' => 'CC', 'slug' => 'cc'],
            ['car_brand_id' => 2, 'name' => 'Corrado', 'slug' => 'corrado'],
            ['car_brand_id' => 2, 'name' => 'Crafter', 'slug' => 'crafter'],
            ['car_brand_id' => 2, 'name' => 'Eos', 'slug' => 'eos'],
            ['car_brand_id' => 2, 'name' => 'Fox', 'slug' => 'fox'],
            ['car_brand_id' => 2, 'name' => 'Garbus', 'slug' => 'garbus'],
            ['car_brand_id' => 2, 'name' => 'Golf', 'slug' => 'golf'],
            ['car_brand_id' => 2, 'name' => 'Golf Plus', 'slug' => 'golf-plus'],
            ['car_brand_id' => 2, 'name' => 'Golf Sportsvan', 'slug' => 'golf-sportsvan'],
            ['car_brand_id' => 2, 'name' => 'ID. Buzz', 'slug' => 'id-buzz'],
            ['car_brand_id' => 2, 'name' => 'ID.3', 'slug' => 'id3'],
            ['car_brand_id' => 2, 'name' => 'ID.4', 'slug' => 'id4'],
            ['car_brand_id' => 2, 'name' => 'ID.5', 'slug' => 'id5'],
            ['car_brand_id' => 2, 'name' => 'ID.6', 'slug' => 'id-6'],
            ['car_brand_id' => 2, 'name' => 'ID.7', 'slug' => 'id-7'],
            ['car_brand_id' => 2, 'name' => 'Iltis', 'slug' => 'iltis'],
            ['car_brand_id' => 2, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 2, 'name' => 'Jetta', 'slug' => 'jetta'],
            ['car_brand_id' => 2, 'name' => 'Kafer', 'slug' => 'kafer'],
            ['car_brand_id' => 2, 'name' => 'Karmann Ghia', 'slug' => 'karmann-ghia'],
            ['car_brand_id' => 2, 'name' => 'LT', 'slug' => 'lt'],
            ['car_brand_id' => 2, 'name' => 'Lupo', 'slug' => 'lupo'],
            ['car_brand_id' => 2, 'name' => 'Multivan', 'slug' => 'multivan'],
            ['car_brand_id' => 2, 'name' => 'New Beetle', 'slug' => 'new-beetle'],
            ['car_brand_id' => 2, 'name' => 'Passat', 'slug' => 'passat'],
            ['car_brand_id' => 2, 'name' => 'Passat Alltrack', 'slug' => 'passat-alltrack'],
            ['car_brand_id' => 2, 'name' => 'Passat CC', 'slug' => 'passat-cc'],
            ['car_brand_id' => 2, 'name' => 'Phaeton', 'slug' => 'phaeton'],
            ['car_brand_id' => 2, 'name' => 'Polo', 'slug' => 'polo'],
            ['car_brand_id' => 2, 'name' => 'Polo Cross', 'slug' => 'polo-cross'],
            ['car_brand_id' => 2, 'name' => 'Routan', 'slug' => 'routan'],
            ['car_brand_id' => 2, 'name' => 'Santana', 'slug' => 'santana'],
            ['car_brand_id' => 2, 'name' => 'Scirocco', 'slug' => 'scirocco'],
            ['car_brand_id' => 2, 'name' => 'Sharan', 'slug' => 'sharan'],
            ['car_brand_id' => 2, 'name' => 'T-Cross', 'slug' => 't-cross'],
            ['car_brand_id' => 2, 'name' => 'T-Roc', 'slug' => 't-roc'],
            ['car_brand_id' => 2, 'name' => 'Taigo', 'slug' => 'taigo'],
            ['car_brand_id' => 2, 'name' => 'Teramont', 'slug' => 'teramont'],
            ['car_brand_id' => 2, 'name' => 'Tiguan', 'slug' => 'tiguan'],
            ['car_brand_id' => 2, 'name' => 'Tiguan Allspace', 'slug' => 'tiguan-allspace'],
            ['car_brand_id' => 2, 'name' => 'Touareg', 'slug' => 'touareg'],
            ['car_brand_id' => 2, 'name' => 'Touran', 'slug' => 'touran'],
            ['car_brand_id' => 2, 'name' => 'Transporter', 'slug' => 'transporter'],
            ['car_brand_id' => 2, 'name' => 'up!', 'slug' => 'up'],
            ['car_brand_id' => 2, 'name' => 'Vento', 'slug' => 'vento'],
            ['car_brand_id' => 3, 'name' => '1M', 'slug' => '1m'],
            ['car_brand_id' => 3, 'name' => '3GT', 'slug' => '3gt'],
            ['car_brand_id' => 3, 'name' => '5GT', 'slug' => '5gt'],
            ['car_brand_id' => 3, 'name' => '6GT', 'slug' => '6gt'],
            ['car_brand_id' => 3, 'name' => 'i3', 'slug' => 'i3'],
            ['car_brand_id' => 3, 'name' => 'i4', 'slug' => 'i4'],
            ['car_brand_id' => 3, 'name' => 'i5', 'slug' => 'i5'],
            ['car_brand_id' => 3, 'name' => 'i7', 'slug' => 'i7'],
            ['car_brand_id' => 3, 'name' => 'i8', 'slug' => 'i8'],
            ['car_brand_id' => 3, 'name' => 'iX', 'slug' => 'ix'],
            ['car_brand_id' => 3, 'name' => 'iX1', 'slug' => 'ix1'],
            ['car_brand_id' => 3, 'name' => 'iX2', 'slug' => 'ix2'],
            ['car_brand_id' => 3, 'name' => 'iX3', 'slug' => 'ix3'],
            ['car_brand_id' => 3, 'name' => 'M2', 'slug' => 'm2'],
            ['car_brand_id' => 3, 'name' => 'M3', 'slug' => 'm3'],
            ['car_brand_id' => 3, 'name' => 'M4', 'slug' => 'm4'],
            ['car_brand_id' => 3, 'name' => 'M5', 'slug' => 'm5'],
            ['car_brand_id' => 3, 'name' => 'M6', 'slug' => 'm6'],
            ['car_brand_id' => 3, 'name' => 'M8', 'slug' => 'm8'],
            ['car_brand_id' => 3, 'name' => 'Seria 1', 'slug' => 'seria-1'],
            ['car_brand_id' => 3, 'name' => 'Seria 2', 'slug' => 'seria-2'],
            ['car_brand_id' => 3, 'name' => 'Seria 3', 'slug' => 'seria-3'],
            ['car_brand_id' => 3, 'name' => 'Seria 4', 'slug' => 'seria-4'],
            ['car_brand_id' => 3, 'name' => 'Seria 5', 'slug' => 'seria-5'],
            ['car_brand_id' => 3, 'name' => 'Seria 6', 'slug' => 'seria-6'],
            ['car_brand_id' => 3, 'name' => 'Seria 7', 'slug' => 'seria-7'],
            ['car_brand_id' => 3, 'name' => 'Seria 8', 'slug' => 'seria-8'],
            ['car_brand_id' => 3, 'name' => 'X1', 'slug' => 'x1'],
            ['car_brand_id' => 3, 'name' => 'X2', 'slug' => 'x2'],
            ['car_brand_id' => 3, 'name' => 'X3', 'slug' => 'x3'],
            ['car_brand_id' => 3, 'name' => 'X3 M', 'slug' => 'x3-m'],
            ['car_brand_id' => 3, 'name' => 'X4', 'slug' => 'x4'],
            ['car_brand_id' => 3, 'name' => 'X4 M', 'slug' => 'x4-m'],
            ['car_brand_id' => 3, 'name' => 'X5', 'slug' => 'x5'],
            ['car_brand_id' => 3, 'name' => 'X5 M', 'slug' => 'x5-m'],
            ['car_brand_id' => 3, 'name' => 'X6', 'slug' => 'x6'],
            ['car_brand_id' => 3, 'name' => 'X6M', 'slug' => 'x6-m'],
            ['car_brand_id' => 3, 'name' => 'X7', 'slug' => 'x7'],
            ['car_brand_id' => 3, 'name' => 'XM', 'slug' => 'xm'],
            ['car_brand_id' => 3, 'name' => 'Z1', 'slug' => 'z1'],
            ['car_brand_id' => 3, 'name' => 'Z3', 'slug' => 'z3'],
            ['car_brand_id' => 3, 'name' => 'Z4', 'slug' => 'z4'],
            ['car_brand_id' => 3, 'name' => 'Z4 M', 'slug' => 'z4-m'],
            ['car_brand_id' => 3, 'name' => 'Z8', 'slug' => 'z8'],
            ['car_brand_id' => 4, 'name' => '280', 'slug' => '280'],
            ['car_brand_id' => 4, 'name' => 'AMG GT', 'slug' => 'amg-gt'],
            ['car_brand_id' => 4, 'name' => 'Citan', 'slug' => 'citan'],
            ['car_brand_id' => 4, 'name' => 'CL', 'slug' => 'cl'],
            ['car_brand_id' => 4, 'name' => 'CLA', 'slug' => 'cla'],
            ['car_brand_id' => 4, 'name' => 'CLC', 'slug' => 'clc'],
            ['car_brand_id' => 4, 'name' => 'CLE', 'slug' => 'cle'],
            ['car_brand_id' => 4, 'name' => 'CLK', 'slug' => 'clk'],
            ['car_brand_id' => 4, 'name' => 'CLS', 'slug' => 'cls'],
            ['car_brand_id' => 4, 'name' => 'EQA', 'slug' => 'eqa'],
            ['car_brand_id' => 4, 'name' => 'EQB', 'slug' => 'eqb'],
            ['car_brand_id' => 4, 'name' => 'EQC', 'slug' => 'eqc'],
            ['car_brand_id' => 4, 'name' => 'EQE', 'slug' => 'eqe'],
            ['car_brand_id' => 4, 'name' => 'EQS', 'slug' => 'eqs'],
            ['car_brand_id' => 4, 'name' => 'EQS 680 SUV', 'slug' => 'eqs-680-suv'],
            ['car_brand_id' => 4, 'name' => 'EQT', 'slug' => 'eqt'],
            ['car_brand_id' => 4, 'name' => 'EQV', 'slug' => 'eqv'],
            ['car_brand_id' => 4, 'name' => 'GL', 'slug' => 'gl'],
            ['car_brand_id' => 4, 'name' => 'GLA', 'slug' => 'gla'],
            ['car_brand_id' => 4, 'name' => 'GLB', 'slug' => 'glb'],
            ['car_brand_id' => 4, 'name' => 'GLC', 'slug' => 'glc'],
            ['car_brand_id' => 4, 'name' => 'GLE', 'slug' => 'gle'],
            ['car_brand_id' => 4, 'name' => 'GLK', 'slug' => 'glk'],
            ['car_brand_id' => 4, 'name' => 'GLS', 'slug' => 'gls'],
            ['car_brand_id' => 4, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 4, 'name' => 'Klasa A', 'slug' => 'klasa-a'],
            ['car_brand_id' => 4, 'name' => 'Klasa B', 'slug' => 'klasa-b'],
            ['car_brand_id' => 4, 'name' => 'Klasa C', 'slug' => 'klasa-c'],
            ['car_brand_id' => 4, 'name' => 'Klasa E', 'slug' => 'klasa-e'],
            ['car_brand_id' => 4, 'name' => 'Klasa G', 'slug' => 'klasa-g'],
            ['car_brand_id' => 4, 'name' => 'Klasa R', 'slug' => 'klasa-r'],
            ['car_brand_id' => 4, 'name' => 'Klasa S', 'slug' => 'klasa-s'],
            ['car_brand_id' => 4, 'name' => 'Klasa T', 'slug' => 't-klasa'],
            ['car_brand_id' => 4, 'name' => 'Klasa V', 'slug' => 'klasa-v'],
            ['car_brand_id' => 4, 'name' => 'Klasa X', 'slug' => 'x-klasa'],
            ['car_brand_id' => 4, 'name' => 'Maybach GLS', 'slug' => 'maybach-gls'],
            ['car_brand_id' => 4, 'name' => 'Maybach Klasa S', 'slug' => 'maybach-s680'],
            ['car_brand_id' => 4, 'name' => 'Maybach SL 680', 'slug' => 'maybach-sl-680'],
            ['car_brand_id' => 4, 'name' => 'MB 100', 'slug' => 'mb-100'],
            ['car_brand_id' => 4, 'name' => 'ML', 'slug' => 'ml'],
            ['car_brand_id' => 4, 'name' => 'Monarch', 'slug' => 'monarch'],
            ['car_brand_id' => 4, 'name' => 'SL', 'slug' => 'sl'],
            ['car_brand_id' => 4, 'name' => 'SLC', 'slug' => 'slc'],
            ['car_brand_id' => 4, 'name' => 'SLK', 'slug' => 'slk'],
            ['car_brand_id' => 4, 'name' => 'SLR', 'slug' => 'slr'],
            ['car_brand_id' => 4, 'name' => 'SLS', 'slug' => 'sls'],
            ['car_brand_id' => 4, 'name' => 'Sprinter', 'slug' => 'sprinter'],
            ['car_brand_id' => 4, 'name' => 'Vaneo', 'slug' => 'vaneo'],
            ['car_brand_id' => 4, 'name' => 'Vario', 'slug' => 'vario'],
            ['car_brand_id' => 4, 'name' => 'Viano', 'slug' => 'viano'],
            ['car_brand_id' => 4, 'name' => 'Vito', 'slug' => 'vito'],
            ['car_brand_id' => 4, 'name' => 'W123', 'slug' => 'w123'],
            ['car_brand_id' => 4, 'name' => 'W124 (1984-1993)', 'slug' => 'w124-1984-1993'],
            ['car_brand_id' => 4, 'name' => 'W201 (190)', 'slug' => 'w201-190'],
            ['car_brand_id' => 5, 'name' => 'Accord', 'slug' => 'accord'],
            ['car_brand_id' => 5, 'name' => 'Aerodeck', 'slug' => 'aerodeck'],
            ['car_brand_id' => 5, 'name' => 'City', 'slug' => 'city'],
            ['car_brand_id' => 5, 'name' => 'Civic', 'slug' => 'civic'],
            ['car_brand_id' => 5, 'name' => 'Clarity', 'slug' => 'clarity'],
            ['car_brand_id' => 5, 'name' => 'Concerto', 'slug' => 'concerto'],
            ['car_brand_id' => 5, 'name' => 'CR-V', 'slug' => 'cr-v'],
            ['car_brand_id' => 5, 'name' => 'CR-Z', 'slug' => 'cr-z'],
            ['car_brand_id' => 5, 'name' => 'CRX', 'slug' => 'crx'],
            ['car_brand_id' => 5, 'name' => 'e', 'slug' => 'e'],
            ['car_brand_id' => 5, 'name' => 'e:NP1', 'slug' => 'e-np1'],
            ['car_brand_id' => 5, 'name' => 'e:NSP1', 'slug' => 'e-nsp1'],
            ['car_brand_id' => 5, 'name' => 'e:NY1', 'slug' => 'e-ny1'],
            ['car_brand_id' => 5, 'name' => 'Element', 'slug' => 'element'],
            ['car_brand_id' => 5, 'name' => 'FR-V', 'slug' => 'fr-v'],
            ['car_brand_id' => 5, 'name' => 'HR-V', 'slug' => 'hr-v'],
            ['car_brand_id' => 5, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 5, 'name' => 'Insight', 'slug' => 'insight'],
            ['car_brand_id' => 5, 'name' => 'Integra', 'slug' => 'integra'],
            ['car_brand_id' => 5, 'name' => 'Jazz', 'slug' => 'jazz'],
            ['car_brand_id' => 5, 'name' => 'Legend', 'slug' => 'legend'],
            ['car_brand_id' => 5, 'name' => 'Logo', 'slug' => 'logo'],
            ['car_brand_id' => 5, 'name' => 'NSX', 'slug' => 'nsx'],
            ['car_brand_id' => 5, 'name' => 'Odyssey', 'slug' => 'odyssey'],
            ['car_brand_id' => 5, 'name' => 'Pilot', 'slug' => 'pilot'],
            ['car_brand_id' => 5, 'name' => 'Prelude', 'slug' => 'prelude'],
            ['car_brand_id' => 5, 'name' => 'Ridgeline', 'slug' => 'ridgeline'],
            ['car_brand_id' => 5, 'name' => 'S 2000', 'slug' => 's-2000'],
            ['car_brand_id' => 5, 'name' => 'Shuttle', 'slug' => 'shuttle'],
            ['car_brand_id' => 5, 'name' => 'Stream', 'slug' => 'stream'],
            ['car_brand_id' => 5, 'name' => 'ZR-V', 'slug' => 'zr-v'],
            ['car_brand_id' => 6, 'name' => 'Aerostar', 'slug' => 'aerostar'],
            ['car_brand_id' => 6, 'name' => 'Aspire', 'slug' => 'aspire'],
            ['car_brand_id' => 6, 'name' => 'B-MAX', 'slug' => 'b-max'],
            ['car_brand_id' => 6, 'name' => 'Bronco', 'slug' => 'bronco'],
            ['car_brand_id' => 6, 'name' => 'C-MAX', 'slug' => 'c-max'],
            ['car_brand_id' => 6, 'name' => 'Capri', 'slug' => 'capri'],
            ['car_brand_id' => 6, 'name' => 'Contour', 'slug' => 'contour'],
            ['car_brand_id' => 6, 'name' => 'Cougar', 'slug' => 'cougar'],
            ['car_brand_id' => 6, 'name' => 'Courier', 'slug' => 'courier'],
            ['car_brand_id' => 6, 'name' => 'Crown', 'slug' => 'crown'],
            ['car_brand_id' => 6, 'name' => 'Econoline', 'slug' => 'econoline'],
            ['car_brand_id' => 6, 'name' => 'Econovan', 'slug' => 'econovan'],
            ['car_brand_id' => 6, 'name' => 'EcoSport', 'slug' => 'ecosport'],
            ['car_brand_id' => 6, 'name' => 'Edge', 'slug' => 'edge'],
            ['car_brand_id' => 6, 'name' => 'Escape', 'slug' => 'escape'],
            ['car_brand_id' => 6, 'name' => 'Escort', 'slug' => 'escort'],
            ['car_brand_id' => 6, 'name' => 'Excursion', 'slug' => 'excursion'],
            ['car_brand_id' => 6, 'name' => 'Expedition', 'slug' => 'expedition'],
            ['car_brand_id' => 6, 'name' => 'Explorer', 'slug' => 'explorer'],
            ['car_brand_id' => 6, 'name' => 'F150', 'slug' => 'f150'],
            ['car_brand_id' => 6, 'name' => 'F250', 'slug' => 'f250'],
            ['car_brand_id' => 6, 'name' => 'F350', 'slug' => 'f350'],
            ['car_brand_id' => 6, 'name' => 'Fairlane', 'slug' => 'fairlane'],
            ['car_brand_id' => 6, 'name' => 'Falcon', 'slug' => 'falcon'],
            ['car_brand_id' => 6, 'name' => 'Festiva', 'slug' => 'festiva'],
            ['car_brand_id' => 6, 'name' => 'Fiesta', 'slug' => 'fiesta'],
            ['car_brand_id' => 6, 'name' => 'FIVE HUNDRED', 'slug' => 'five-hundred'],
            ['car_brand_id' => 6, 'name' => 'Flex', 'slug' => 'flex'],
            ['car_brand_id' => 6, 'name' => 'Focus', 'slug' => 'focus'],
            ['car_brand_id' => 6, 'name' => 'Focus C-Max', 'slug' => 'focus-c-max'],
            ['car_brand_id' => 6, 'name' => 'Freestar', 'slug' => 'freestar'],
            ['car_brand_id' => 6, 'name' => 'Freestyle', 'slug' => 'freestyle'],
            ['car_brand_id' => 6, 'name' => 'Fusion', 'slug' => 'fusion'],
            ['car_brand_id' => 6, 'name' => 'Galaxy', 'slug' => 'galaxy'],
            ['car_brand_id' => 6, 'name' => 'Granada', 'slug' => 'granada'],
            ['car_brand_id' => 6, 'name' => 'Grand C-MAX', 'slug' => 'grand-c-max'],
            ['car_brand_id' => 6, 'name' => 'GT', 'slug' => 'gt'],
            ['car_brand_id' => 6, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 6, 'name' => 'KA', 'slug' => 'ka'],
            ['car_brand_id' => 6, 'name' => 'Ka+', 'slug' => 'ka_plus'],
            ['car_brand_id' => 6, 'name' => 'Kuga', 'slug' => 'kuga'],
            ['car_brand_id' => 6, 'name' => 'Maverick', 'slug' => 'maverick'],
            ['car_brand_id' => 6, 'name' => 'Mercury', 'slug' => 'mercury'],
            ['car_brand_id' => 6, 'name' => 'Mondeo', 'slug' => 'mondeo'],
            ['car_brand_id' => 6, 'name' => 'Mustang', 'slug' => 'mustang'],
            ['car_brand_id' => 6, 'name' => 'Mustang Mach-E', 'slug' => 'mustang-mach-e'],
            ['car_brand_id' => 6, 'name' => 'Orion', 'slug' => 'orion'],
            ['car_brand_id' => 6, 'name' => 'Probe', 'slug' => 'probe'],
            ['car_brand_id' => 6, 'name' => 'Puma', 'slug' => 'puma'],
            ['car_brand_id' => 6, 'name' => 'Ranchero', 'slug' => 'ranchero'],
            ['car_brand_id' => 6, 'name' => 'Ranger', 'slug' => 'ranger'],
            ['car_brand_id' => 6, 'name' => 'Ranger Raptor', 'slug' => 'ranger-raptor'],
            ['car_brand_id' => 6, 'name' => 'S-Max', 'slug' => 's-max'],
            ['car_brand_id' => 6, 'name' => 'Scorpio', 'slug' => 'scorpio'],
            ['car_brand_id' => 6, 'name' => 'Sierra', 'slug' => 'sierra'],
            ['car_brand_id' => 6, 'name' => 'Streetka', 'slug' => 'streetka'],
            ['car_brand_id' => 6, 'name' => 'Taunus', 'slug' => 'taunus'],
            ['car_brand_id' => 6, 'name' => 'Taurus', 'slug' => 'taurus'],
            ['car_brand_id' => 6, 'name' => 'Tempo', 'slug' => 'tempo'],
            ['car_brand_id' => 6, 'name' => 'Thunderbird', 'slug' => 'thunderbird'],
            ['car_brand_id' => 6, 'name' => 'Tourneo Connect', 'slug' => 'tourneo-connect'],
            ['car_brand_id' => 6, 'name' => 'Tourneo Connect Grand', 'slug' => 'grand-tourneo-connect'],
            ['car_brand_id' => 6, 'name' => 'Tourneo Courier', 'slug' => 'tourneo-courier'],
            ['car_brand_id' => 6, 'name' => 'Tourneo Custom', 'slug' => 'tourneo-custom'],
            ['car_brand_id' => 6, 'name' => 'Transit', 'slug' => 'transit'],
            ['car_brand_id' => 6, 'name' => 'Transit Connect', 'slug' => 'transit-connect'],
            ['car_brand_id' => 6, 'name' => 'Transit Courier', 'slug' => 'transit-courier'],
            ['car_brand_id' => 6, 'name' => 'Transit Custom', 'slug' => 'transit-custom'],
            ['car_brand_id' => 6, 'name' => 'Windstar', 'slug' => 'windstar'],
            ['car_brand_id' => 7, 'name' => '100', 'slug' => '100'],
            ['car_brand_id' => 7, 'name' => '200', 'slug' => '200'],
            ['car_brand_id' => 7, 'name' => '80', 'slug' => '80'],
            ['car_brand_id' => 7, 'name' => '90', 'slug' => '90'],
            ['car_brand_id' => 7, 'name' => 'A1', 'slug' => 'a1'],
            ['car_brand_id' => 7, 'name' => 'A2', 'slug' => 'a2'],
            ['car_brand_id' => 7, 'name' => 'A3', 'slug' => 'a3'],
            ['car_brand_id' => 7, 'name' => 'A4', 'slug' => 'a4'],
            ['car_brand_id' => 7, 'name' => 'A4 Allroad', 'slug' => 'a4-allroad'],
            ['car_brand_id' => 7, 'name' => 'A5', 'slug' => 'a5'],
            ['car_brand_id' => 7, 'name' => 'A6', 'slug' => 'a6'],
            ['car_brand_id' => 7, 'name' => 'A6 Allroad', 'slug' => 'a6-allroad'],
            ['car_brand_id' => 7, 'name' => 'A7', 'slug' => 'a7'],
            ['car_brand_id' => 7, 'name' => 'A8', 'slug' => 'a8'],
            ['car_brand_id' => 7, 'name' => 'Cabriolet', 'slug' => 'cabriolet'],
            ['car_brand_id' => 7, 'name' => 'Coupe', 'slug' => 'coupe'],
            ['car_brand_id' => 7, 'name' => 'e-tron', 'slug' => 'e-tron'],
            ['car_brand_id' => 7, 'name' => 'e-tron GT', 'slug' => 'e-tron-gt'],
            ['car_brand_id' => 7, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 7, 'name' => 'Q2', 'slug' => 'q2'],
            ['car_brand_id' => 7, 'name' => 'Q3', 'slug' => 'q3'],
            ['car_brand_id' => 7, 'name' => 'Q3 Sportback', 'slug' => 'q3-sportback'],
            ['car_brand_id' => 7, 'name' => 'Q4', 'slug' => 'q4'],
            ['car_brand_id' => 7, 'name' => 'Q4 Sportback', 'slug' => 'q4-sportback'],
            ['car_brand_id' => 7, 'name' => 'Q5', 'slug' => 'q5'],
            ['car_brand_id' => 7, 'name' => 'Q5 Sportback', 'slug' => 'q5-sportback'],
            ['car_brand_id' => 7, 'name' => 'Q6', 'slug' => 'q6'],
            ['car_brand_id' => 7, 'name' => 'Q7', 'slug' => 'q7'],
            ['car_brand_id' => 7, 'name' => 'Q8', 'slug' => 'q8'],
            ['car_brand_id' => 7, 'name' => 'Quattro', 'slug' => 'quattro'],
            ['car_brand_id' => 7, 'name' => 'R8', 'slug' => 'r8'],
            ['car_brand_id' => 7, 'name' => 'RS e-tron GT', 'slug' => 'rs-e-tron-gt'],
            ['car_brand_id' => 7, 'name' => 'RS Q3', 'slug' => 'rs-q3'],
            ['car_brand_id' => 7, 'name' => 'RS Q8', 'slug' => 'rs-q8'],
            ['car_brand_id' => 7, 'name' => 'RS2', 'slug' => 'rs2'],
            ['car_brand_id' => 7, 'name' => 'RS3', 'slug' => 'rs3'],
            ['car_brand_id' => 7, 'name' => 'RS4', 'slug' => 'rs4'],
            ['car_brand_id' => 7, 'name' => 'RS5', 'slug' => 'rs5'],
            ['car_brand_id' => 7, 'name' => 'RS6', 'slug' => 'rs6'],
            ['car_brand_id' => 7, 'name' => 'RS7', 'slug' => 'rs7'],
            ['car_brand_id' => 7, 'name' => 'S1', 'slug' => 's1'],
            ['car_brand_id' => 7, 'name' => 'S2', 'slug' => 's2'],
            ['car_brand_id' => 7, 'name' => 'S3', 'slug' => 's3'],
            ['car_brand_id' => 7, 'name' => 'S4', 'slug' => 's4'],
            ['car_brand_id' => 7, 'name' => 'S5', 'slug' => 's5'],
            ['car_brand_id' => 7, 'name' => 'S6', 'slug' => 's6'],
            ['car_brand_id' => 7, 'name' => 'S7', 'slug' => 's7'],
            ['car_brand_id' => 7, 'name' => 'S8', 'slug' => 's8'],
            ['car_brand_id' => 7, 'name' => 'SQ2', 'slug' => 'sq2'],
            ['car_brand_id' => 7, 'name' => 'SQ5', 'slug' => 'sq5'],
            ['car_brand_id' => 7, 'name' => 'SQ6', 'slug' => 'sq6'],
            ['car_brand_id' => 7, 'name' => 'SQ7', 'slug' => 'sq7'],
            ['car_brand_id' => 7, 'name' => 'SQ8', 'slug' => 'sq8'],
            ['car_brand_id' => 7, 'name' => 'TT', 'slug' => 'tt'],
            ['car_brand_id' => 7, 'name' => 'TT RS', 'slug' => 'tt-rs'],
            ['car_brand_id' => 7, 'name' => 'TT S', 'slug' => 'tt-s'],
            ['car_brand_id' => 7, 'name' => 'V8', 'slug' => 'v8'],
            ['car_brand_id' => 8, 'name' => '1007', 'slug' => '1007'],
            ['car_brand_id' => 8, 'name' => '104', 'slug' => '104'],
            ['car_brand_id' => 8, 'name' => '106', 'slug' => '106'],
            ['car_brand_id' => 8, 'name' => '107', 'slug' => '107'],
            ['car_brand_id' => 8, 'name' => '108', 'slug' => '108'],
            ['car_brand_id' => 8, 'name' => '2008', 'slug' => '2008'],
            ['car_brand_id' => 8, 'name' => '204', 'slug' => '204'],
            ['car_brand_id' => 8, 'name' => '205', 'slug' => '205'],
            ['car_brand_id' => 8, 'name' => '206', 'slug' => '206'],
            ['car_brand_id' => 8, 'name' => '206 CC', 'slug' => '206-cc'],
            ['car_brand_id' => 8, 'name' => '206 plus', 'slug' => '206-plus'],
            ['car_brand_id' => 8, 'name' => '207', 'slug' => '207'],
            ['car_brand_id' => 8, 'name' => '207 CC', 'slug' => '207-cc'],
            ['car_brand_id' => 8, 'name' => '208', 'slug' => '208'],
            ['car_brand_id' => 8, 'name' => '3008', 'slug' => '3008'],
            ['car_brand_id' => 8, 'name' => '301', 'slug' => '301'],
            ['car_brand_id' => 8, 'name' => '304', 'slug' => '304'],
            ['car_brand_id' => 8, 'name' => '305', 'slug' => '305'],
            ['car_brand_id' => 8, 'name' => '306', 'slug' => '306'],
            ['car_brand_id' => 8, 'name' => '307', 'slug' => '307'],
            ['car_brand_id' => 8, 'name' => '307 CC', 'slug' => '307-cc'],
            ['car_brand_id' => 8, 'name' => '308', 'slug' => '308'],
            ['car_brand_id' => 8, 'name' => '308 CC', 'slug' => '308-cc'],
            ['car_brand_id' => 8, 'name' => '309', 'slug' => '309'],
            ['car_brand_id' => 8, 'name' => '395', 'slug' => '395'],
            ['car_brand_id' => 8, 'name' => '4007', 'slug' => '4007'],
            ['car_brand_id' => 8, 'name' => '4008', 'slug' => '4008'],
            ['car_brand_id' => 8, 'name' => '404', 'slug' => '404'],
            ['car_brand_id' => 8, 'name' => '405', 'slug' => '405'],
            ['car_brand_id' => 8, 'name' => '406', 'slug' => '406'],
            ['car_brand_id' => 8, 'name' => '407', 'slug' => '407'],
            ['car_brand_id' => 8, 'name' => '408', 'slug' => '408'],
            ['car_brand_id' => 8, 'name' => '5008', 'slug' => '5008'],
            ['car_brand_id' => 8, 'name' => '504', 'slug' => '504'],
            ['car_brand_id' => 8, 'name' => '505', 'slug' => '505'],
            ['car_brand_id' => 8, 'name' => '508', 'slug' => '508'],
            ['car_brand_id' => 8, 'name' => '604', 'slug' => '604'],
            ['car_brand_id' => 8, 'name' => '605', 'slug' => '605'],
            ['car_brand_id' => 8, 'name' => '607', 'slug' => '607'],
            ['car_brand_id' => 8, 'name' => '806', 'slug' => '806'],
            ['car_brand_id' => 8, 'name' => '807', 'slug' => '807'],
            ['car_brand_id' => 8, 'name' => 'Bipper', 'slug' => 'bipper'],
            ['car_brand_id' => 8, 'name' => 'Boxer', 'slug' => 'boxer'],
            ['car_brand_id' => 8, 'name' => 'Expert', 'slug' => 'expert'],
            ['car_brand_id' => 8, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 8, 'name' => 'iOn', 'slug' => 'ion'],
            ['car_brand_id' => 8, 'name' => 'Partner', 'slug' => 'partner'],
            ['car_brand_id' => 8, 'name' => 'RCZ', 'slug' => 'rcz'],
            ['car_brand_id' => 8, 'name' => 'Rifter', 'slug' => 'rifter'],
            ['car_brand_id' => 8, 'name' => 'Traveller', 'slug' => 'traveller'],
            ['car_brand_id' => 9, 'name' => 'Accent', 'slug' => 'accent'],
            ['car_brand_id' => 9, 'name' => 'Atos', 'slug' => 'atos'],
            ['car_brand_id' => 9, 'name' => 'Avante', 'slug' => 'avante'],
            ['car_brand_id' => 9, 'name' => 'Azera', 'slug' => 'azera'],
            ['car_brand_id' => 9, 'name' => 'Bayon', 'slug' => 'bayon'],
            ['car_brand_id' => 9, 'name' => 'Coupe', 'slug' => 'coupe'],
            ['car_brand_id' => 9, 'name' => 'Elantra', 'slug' => 'elantra'],
            ['car_brand_id' => 9, 'name' => 'Equus', 'slug' => 'equus'],
            ['car_brand_id' => 9, 'name' => 'Excel', 'slug' => 'excel'],
            ['car_brand_id' => 9, 'name' => 'Galloper', 'slug' => 'galloper'],
            ['car_brand_id' => 9, 'name' => 'Genesis', 'slug' => 'genesis'],
            ['car_brand_id' => 9, 'name' => 'Genesis Coupe', 'slug' => 'genesis-coupe'],
            ['car_brand_id' => 9, 'name' => 'Getz', 'slug' => 'getz'],
            ['car_brand_id' => 9, 'name' => 'Grand Santa Fe', 'slug' => 'grand-santa-fe'],
            ['car_brand_id' => 9, 'name' => 'Grandeur', 'slug' => 'grandeur'],
            ['car_brand_id' => 9, 'name' => 'H-1', 'slug' => 'h-1'],
            ['car_brand_id' => 9, 'name' => 'H-1 Starex', 'slug' => 'h-1-starex'],
            ['car_brand_id' => 9, 'name' => 'H200', 'slug' => 'h200'],
            ['car_brand_id' => 9, 'name' => 'H350', 'slug' => 'h350'],
            ['car_brand_id' => 9, 'name' => 'i10', 'slug' => 'i10'],
            ['car_brand_id' => 9, 'name' => 'i20', 'slug' => 'i20'],
            ['car_brand_id' => 9, 'name' => 'i25', 'slug' => 'i25'],
            ['car_brand_id' => 9, 'name' => 'i30', 'slug' => 'i30'],
            ['car_brand_id' => 9, 'name' => 'i30 N', 'slug' => 'i30-n'],
            ['car_brand_id' => 9, 'name' => 'i40', 'slug' => 'i40'],
            ['car_brand_id' => 9, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 9, 'name' => 'IONIQ', 'slug' => 'ioniq'],
            ['car_brand_id' => 9, 'name' => 'IONIQ 5', 'slug' => 'ioniq-5'],
            ['car_brand_id' => 9, 'name' => 'IONIQ 6', 'slug' => 'ioniq-6'],
            ['car_brand_id' => 9, 'name' => 'IONIQ 7', 'slug' => 'ioniq-7'],
            ['car_brand_id' => 9, 'name' => 'ix20', 'slug' => 'ix20'],
            ['car_brand_id' => 9, 'name' => 'ix35', 'slug' => 'ix35'],
            ['car_brand_id' => 9, 'name' => 'ix55', 'slug' => 'ix55'],
            ['car_brand_id' => 9, 'name' => 'Kona', 'slug' => 'kona'],
            ['car_brand_id' => 9, 'name' => 'Lantra', 'slug' => 'lantra'],
            ['car_brand_id' => 9, 'name' => 'Matrix', 'slug' => 'matrix'],
            ['car_brand_id' => 9, 'name' => 'NEXO', 'slug' => 'nexo'],
            ['car_brand_id' => 9, 'name' => 'Palisade', 'slug' => 'palisade'],
            ['car_brand_id' => 9, 'name' => 'Pony', 'slug' => 'pony'],
            ['car_brand_id' => 9, 'name' => 'S-Coupe', 'slug' => 's-coupe'],
            ['car_brand_id' => 9, 'name' => 'Santa Cruz', 'slug' => 'santa-cruz'],
            ['car_brand_id' => 9, 'name' => 'Santa Fe', 'slug' => 'santa-fe'],
            ['car_brand_id' => 9, 'name' => 'Santamo', 'slug' => 'santamo'],
            ['car_brand_id' => 9, 'name' => 'Sonata', 'slug' => 'sonata'],
            ['car_brand_id' => 9, 'name' => 'Sonica', 'slug' => 'sonica'],
            ['car_brand_id' => 9, 'name' => 'Staria', 'slug' => 'staria'],
            ['car_brand_id' => 9, 'name' => 'Terracan', 'slug' => 'terracan'],
            ['car_brand_id' => 9, 'name' => 'Trajet', 'slug' => 'trajet'],
            ['car_brand_id' => 9, 'name' => 'Tucson', 'slug' => 'tucson'],
            ['car_brand_id' => 9, 'name' => 'Veloster', 'slug' => 'veloster'],
            ['car_brand_id' => 9, 'name' => 'Veracruz', 'slug' => 'veracruz'],
            ['car_brand_id' => 9, 'name' => 'XG 30', 'slug' => 'xg-30'],
            ['car_brand_id' => 9, 'name' => 'XG 350', 'slug' => 'xg-350'],
            ['car_brand_id' => 10, 'name' => '100 NX', 'slug' => '100-nx'],
            ['car_brand_id' => 10, 'name' => '200 SX', 'slug' => '200-sx'],
            ['car_brand_id' => 10, 'name' => '240 SX', 'slug' => '240-sx'],
            ['car_brand_id' => 10, 'name' => '280 ZX', 'slug' => '280-zx'],
            ['car_brand_id' => 10, 'name' => '300 ZX', 'slug' => '300-zx'],
            ['car_brand_id' => 10, 'name' => '350 Z', 'slug' => '350-z'],
            ['car_brand_id' => 10, 'name' => '370 Z', 'slug' => '370-z'],
            ['car_brand_id' => 10, 'name' => 'Almera', 'slug' => 'almera'],
            ['car_brand_id' => 10, 'name' => 'Almera Tino', 'slug' => 'almera-tino'],
            ['car_brand_id' => 10, 'name' => 'Altima', 'slug' => 'altima'],
            ['car_brand_id' => 10, 'name' => 'Ariya', 'slug' => 'ariya'],
            ['car_brand_id' => 10, 'name' => 'Armada', 'slug' => 'armada'],
            ['car_brand_id' => 10, 'name' => 'Bluebird', 'slug' => 'bluebird'],
            ['car_brand_id' => 10, 'name' => 'Cherry', 'slug' => 'cherry'],
            ['car_brand_id' => 10, 'name' => 'Cube', 'slug' => 'cube'],
            ['car_brand_id' => 10, 'name' => 'Frontier', 'slug' => 'frontier'],
            ['car_brand_id' => 10, 'name' => 'GT-R', 'slug' => 'gt-r'],
            ['car_brand_id' => 10, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 10, 'name' => 'Interstar', 'slug' => 'interstar'],
            ['car_brand_id' => 10, 'name' => 'Juke', 'slug' => 'juke'],
            ['car_brand_id' => 10, 'name' => 'King Cab', 'slug' => 'king-cab'],
            ['car_brand_id' => 10, 'name' => 'Kubistar', 'slug' => 'kubistar'],
            ['car_brand_id' => 10, 'name' => 'Laurel', 'slug' => 'laurel'],
            ['car_brand_id' => 10, 'name' => 'Leaf', 'slug' => 'leaf'],
            ['car_brand_id' => 10, 'name' => 'Maxima', 'slug' => 'maxima'],
            ['car_brand_id' => 10, 'name' => 'Micra', 'slug' => 'micra'],
            ['car_brand_id' => 10, 'name' => 'Murano', 'slug' => 'murano'],
            ['car_brand_id' => 10, 'name' => 'Navara', 'slug' => 'navara'],
            ['car_brand_id' => 10, 'name' => 'Note', 'slug' => 'note'],
            ['car_brand_id' => 10, 'name' => 'NP300 Pickup', 'slug' => 'np300-pickup'],
            ['car_brand_id' => 10, 'name' => 'NV200', 'slug' => 'nv200'],
            ['car_brand_id' => 10, 'name' => 'NV300', 'slug' => 'nv300'],
            ['car_brand_id' => 10, 'name' => 'NV400', 'slug' => 'nv400'],
            ['car_brand_id' => 10, 'name' => 'Pathfinder', 'slug' => 'pathfinder'],
            ['car_brand_id' => 10, 'name' => 'Patrol', 'slug' => 'patrol'],
            ['car_brand_id' => 10, 'name' => 'Pickup', 'slug' => 'pickup'],
            ['car_brand_id' => 10, 'name' => 'Pixo', 'slug' => 'pixo'],
            ['car_brand_id' => 10, 'name' => 'Prairie', 'slug' => 'prairie'],
            ['car_brand_id' => 10, 'name' => 'Primastar', 'slug' => 'primastar'],
            ['car_brand_id' => 10, 'name' => 'Primera', 'slug' => 'primera'],
            ['car_brand_id' => 10, 'name' => 'Pulsar', 'slug' => 'pulsar'],
            ['car_brand_id' => 10, 'name' => 'Qashqai', 'slug' => 'qashqai'],
            ['car_brand_id' => 10, 'name' => 'Qashqai+2', 'slug' => 'qashqai-2'],
            ['car_brand_id' => 10, 'name' => 'Quest', 'slug' => 'quest'],
            ['car_brand_id' => 10, 'name' => 'Rogue', 'slug' => 'rogue'],
            ['car_brand_id' => 10, 'name' => 'Sentra', 'slug' => 'sentra'],
            ['car_brand_id' => 10, 'name' => 'Serena', 'slug' => 'serena'],
            ['car_brand_id' => 10, 'name' => 'Silvia', 'slug' => 'silvia'],
            ['car_brand_id' => 10, 'name' => 'Skyline', 'slug' => 'skyline'],
            ['car_brand_id' => 10, 'name' => 'Stanza', 'slug' => 'stanza'],
            ['car_brand_id' => 10, 'name' => 'Sunny', 'slug' => 'sunny'],
            ['car_brand_id' => 10, 'name' => 'Terrano', 'slug' => 'terrano'],
            ['car_brand_id' => 10, 'name' => 'Tiida', 'slug' => 'tiida'],
            ['car_brand_id' => 10, 'name' => 'Titan', 'slug' => 'titan'],
            ['car_brand_id' => 10, 'name' => 'Townstar', 'slug' => 'townstar'],
            ['car_brand_id' => 10, 'name' => 'Trade', 'slug' => 'trade'],
            ['car_brand_id' => 10, 'name' => 'Urvan', 'slug' => 'urvan'],
            ['car_brand_id' => 10, 'name' => 'Vanette', 'slug' => 'vanette'],
            ['car_brand_id' => 10, 'name' => 'X-Trail', 'slug' => 'x-trail'],
            ['car_brand_id' => 10, 'name' => 'Xterra', 'slug' => 'xterra'],
            ['car_brand_id' => 11, 'name' => 'Adam', 'slug' => 'adam'],
            ['car_brand_id' => 11, 'name' => 'Agila', 'slug' => 'agila'],
            ['car_brand_id' => 11, 'name' => 'Ampera', 'slug' => 'ampera'],
            ['car_brand_id' => 11, 'name' => 'Antara', 'slug' => 'antara'],
            ['car_brand_id' => 11, 'name' => 'Arena', 'slug' => 'arena'],
            ['car_brand_id' => 11, 'name' => 'Ascona', 'slug' => 'ascona'],
            ['car_brand_id' => 11, 'name' => 'Astra', 'slug' => 'astra'],
            ['car_brand_id' => 11, 'name' => 'Calibra', 'slug' => 'calibra'],
            ['car_brand_id' => 11, 'name' => 'Campo', 'slug' => 'campo'],
            ['car_brand_id' => 11, 'name' => 'Cascada', 'slug' => 'cascada'],
            ['car_brand_id' => 11, 'name' => 'Combo', 'slug' => 'combo'],
            ['car_brand_id' => 11, 'name' => 'Commodore', 'slug' => 'commodore'],
            ['car_brand_id' => 11, 'name' => 'Corsa', 'slug' => 'corsa'],
            ['car_brand_id' => 11, 'name' => 'Crossland', 'slug' => 'crossland'],
            ['car_brand_id' => 11, 'name' => 'Crossland X', 'slug' => 'crossland-x'],
            ['car_brand_id' => 11, 'name' => 'Diplomat', 'slug' => 'diplomat'],
            ['car_brand_id' => 11, 'name' => 'Frontera', 'slug' => 'frontera'],
            ['car_brand_id' => 11, 'name' => 'Grandland', 'slug' => 'grandland'],
            ['car_brand_id' => 11, 'name' => 'Grandland X', 'slug' => 'grandland-x'],
            ['car_brand_id' => 11, 'name' => 'GT', 'slug' => 'gt'],
            ['car_brand_id' => 11, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 11, 'name' => 'Insignia', 'slug' => 'insignia'],
            ['car_brand_id' => 11, 'name' => 'Kadett', 'slug' => 'kadett'],
            ['car_brand_id' => 11, 'name' => 'Karl', 'slug' => 'karl'],
            ['car_brand_id' => 11, 'name' => 'Manta', 'slug' => 'manta'],
            ['car_brand_id' => 11, 'name' => 'Meriva', 'slug' => 'meriva'],
            ['car_brand_id' => 11, 'name' => 'Mokka', 'slug' => 'mokka'],
            ['car_brand_id' => 11, 'name' => 'Monterey', 'slug' => 'monterey'],
            ['car_brand_id' => 11, 'name' => 'Monza', 'slug' => 'monza'],
            ['car_brand_id' => 11, 'name' => 'Movano', 'slug' => 'movano'],
            ['car_brand_id' => 11, 'name' => 'Nova', 'slug' => 'nova'],
            ['car_brand_id' => 11, 'name' => 'Omega', 'slug' => 'omega'],
            ['car_brand_id' => 11, 'name' => 'Pick up Sportcap', 'slug' => 'pick-up-sportcap'],
            ['car_brand_id' => 11, 'name' => 'Rekord', 'slug' => 'rekord'],
            ['car_brand_id' => 11, 'name' => 'Senator', 'slug' => 'senator'],
            ['car_brand_id' => 11, 'name' => 'Signum', 'slug' => 'signum'],
            ['car_brand_id' => 11, 'name' => 'Sintra', 'slug' => 'sintra'],
            ['car_brand_id' => 11, 'name' => 'Speedster', 'slug' => 'speedster'],
            ['car_brand_id' => 11, 'name' => 'Tigra', 'slug' => 'tigra'],
            ['car_brand_id' => 11, 'name' => 'Vectra', 'slug' => 'vectra'],
            ['car_brand_id' => 11, 'name' => 'Vivaro', 'slug' => 'vivaro'],
            ['car_brand_id' => 11, 'name' => 'Zafira', 'slug' => 'zafira'],
            ['car_brand_id' => 12, 'name' => 'Asia Rocsta', 'slug' => 'asia-rocsta'],
            ['car_brand_id' => 12, 'name' => 'Besta', 'slug' => 'besta'],
            ['car_brand_id' => 12, 'name' => 'Cadenza', 'slug' => 'cadenza'],
            ['car_brand_id' => 12, 'name' => 'Carens', 'slug' => 'carens'],
            ['car_brand_id' => 12, 'name' => 'Carnival', 'slug' => 'carnival'],
            ['car_brand_id' => 12, 'name' => 'Ceed', 'slug' => 'ceed'],
            ['car_brand_id' => 12, 'name' => 'Cerato', 'slug' => 'cerato'],
            ['car_brand_id' => 12, 'name' => 'Clarus', 'slug' => 'clarus'],
            ['car_brand_id' => 12, 'name' => 'Elan', 'slug' => 'elan'],
            ['car_brand_id' => 12, 'name' => 'EV3', 'slug' => 'ev3'],
            ['car_brand_id' => 12, 'name' => 'EV5', 'slug' => 'ev5'],
            ['car_brand_id' => 12, 'name' => 'EV6', 'slug' => 'ev6'],
            ['car_brand_id' => 12, 'name' => 'EV9', 'slug' => 'ev9'],
            ['car_brand_id' => 12, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 12, 'name' => 'Joice', 'slug' => 'joice'],
            ['car_brand_id' => 12, 'name' => 'Leo', 'slug' => 'leo'],
            ['car_brand_id' => 12, 'name' => 'Magentis', 'slug' => 'magentis'],
            ['car_brand_id' => 12, 'name' => 'Mentor', 'slug' => 'mentor'],
            ['car_brand_id' => 12, 'name' => 'Niro', 'slug' => 'niro'],
            ['car_brand_id' => 12, 'name' => 'Opirus', 'slug' => 'opirus'],
            ['car_brand_id' => 12, 'name' => 'Optima', 'slug' => 'optima'],
            ['car_brand_id' => 12, 'name' => 'Picanto', 'slug' => 'picanto'],
            ['car_brand_id' => 12, 'name' => 'Pregio', 'slug' => 'pregio'],
            ['car_brand_id' => 12, 'name' => 'Pride', 'slug' => 'pride'],
            ['car_brand_id' => 12, 'name' => 'Pro_cee\'d', 'slug' => 'pro-ceed'],
            ['car_brand_id' => 12, 'name' => 'Retona', 'slug' => 'retona'],
            ['car_brand_id' => 12, 'name' => 'Rio', 'slug' => 'rio'],
            ['car_brand_id' => 12, 'name' => 'Roadster', 'slug' => 'roadster'],
            ['car_brand_id' => 12, 'name' => 'Rocsta', 'slug' => 'rocsta'],
            ['car_brand_id' => 12, 'name' => 'Sedona', 'slug' => 'sedona'],
            ['car_brand_id' => 12, 'name' => 'Sephia', 'slug' => 'sephia'],
            ['car_brand_id' => 12, 'name' => 'Shuma', 'slug' => 'shuma'],
            ['car_brand_id' => 12, 'name' => 'Sorento', 'slug' => 'sorento'],
            ['car_brand_id' => 12, 'name' => 'Soul', 'slug' => 'soul'],
            ['car_brand_id' => 12, 'name' => 'Spectra', 'slug' => 'spectra'],
            ['car_brand_id' => 12, 'name' => 'Sportage', 'slug' => 'sportage'],
            ['car_brand_id' => 12, 'name' => 'Stinger', 'slug' => 'stinger'],
            ['car_brand_id' => 12, 'name' => 'Stonic', 'slug' => 'stonic'],
            ['car_brand_id' => 12, 'name' => 'Venga', 'slug' => 'venga'],
            ['car_brand_id' => 12, 'name' => 'XCeed', 'slug' => 'xceed'],
            ['car_brand_id' => 13, 'name' => '100', 'slug' => '100'],
            ['car_brand_id' => 13, 'name' => '105', 'slug' => '105'],
            ['car_brand_id' => 13, 'name' => '120', 'slug' => '120'],
            ['car_brand_id' => 13, 'name' => '130', 'slug' => '130'],
            ['car_brand_id' => 13, 'name' => '135', 'slug' => '135'],
            ['car_brand_id' => 13, 'name' => 'Citigo', 'slug' => 'citigo'],
            ['car_brand_id' => 13, 'name' => 'Enyaq', 'slug' => 'enyaq'],
            ['car_brand_id' => 13, 'name' => 'Fabia', 'slug' => 'fabia'],
            ['car_brand_id' => 13, 'name' => 'Favorit', 'slug' => 'favorit'],
            ['car_brand_id' => 13, 'name' => 'Felicia', 'slug' => 'felicia'],
            ['car_brand_id' => 13, 'name' => 'Forman', 'slug' => 'forman'],
            ['car_brand_id' => 13, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 13, 'name' => 'Kamiq', 'slug' => 'kamiq'],
            ['car_brand_id' => 13, 'name' => 'Karoq', 'slug' => 'karoq'],
            ['car_brand_id' => 13, 'name' => 'Kodiaq', 'slug' => 'kodiaq'],
            ['car_brand_id' => 13, 'name' => 'Octavia', 'slug' => 'octavia'],
            ['car_brand_id' => 13, 'name' => 'Praktik', 'slug' => 'praktik'],
            ['car_brand_id' => 13, 'name' => 'RAPID', 'slug' => 'rapid'],
            ['car_brand_id' => 13, 'name' => 'Roomster', 'slug' => 'roomster'],
            ['car_brand_id' => 13, 'name' => 'Scala', 'slug' => 'scala'],
            ['car_brand_id' => 13, 'name' => 'Superb', 'slug' => 'superb'],
            ['car_brand_id' => 13, 'name' => 'Yeti', 'slug' => 'yeti'],
            ['car_brand_id' => 14, 'name' => '121', 'slug' => '121'],
            ['car_brand_id' => 14, 'name' => '2', 'slug' => '2'],
            ['car_brand_id' => 14, 'name' => '3', 'slug' => '3'],
            ['car_brand_id' => 14, 'name' => '323', 'slug' => '323'],
            ['car_brand_id' => 14, 'name' => '323F', 'slug' => '323f'],
            ['car_brand_id' => 14, 'name' => '5', 'slug' => '5'],
            ['car_brand_id' => 14, 'name' => '6', 'slug' => '6'],
            ['car_brand_id' => 14, 'name' => '626', 'slug' => '626'],
            ['car_brand_id' => 14, 'name' => '929', 'slug' => '929'],
            ['car_brand_id' => 14, 'name' => 'Bongo', 'slug' => 'bongo'],
            ['car_brand_id' => 14, 'name' => 'BT-50', 'slug' => 'bt-50'],
            ['car_brand_id' => 14, 'name' => 'CX-3', 'slug' => 'cx-3'],
            ['car_brand_id' => 14, 'name' => 'CX-30', 'slug' => 'cx-30'],
            ['car_brand_id' => 14, 'name' => 'CX-5', 'slug' => 'cx-5'],
            ['car_brand_id' => 14, 'name' => 'CX-50', 'slug' => 'cx-50'],
            ['car_brand_id' => 14, 'name' => 'CX-60', 'slug' => 'cx-60'],
            ['car_brand_id' => 14, 'name' => 'CX-7', 'slug' => 'cx-7'],
            ['car_brand_id' => 14, 'name' => 'CX-80', 'slug' => 'cx-80'],
            ['car_brand_id' => 14, 'name' => 'CX-9', 'slug' => 'cx-9'],
            ['car_brand_id' => 14, 'name' => 'CX-90', 'slug' => 'cx-90'],
            ['car_brand_id' => 14, 'name' => 'Demio', 'slug' => 'demio'],
            ['car_brand_id' => 14, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 14, 'name' => 'Millenia', 'slug' => 'millenia'],
            ['car_brand_id' => 14, 'name' => 'MPV', 'slug' => 'mpv'],
            ['car_brand_id' => 14, 'name' => 'MX-3', 'slug' => 'mx-3'],
            ['car_brand_id' => 14, 'name' => 'MX-30', 'slug' => 'mx-30'],
            ['car_brand_id' => 14, 'name' => 'MX-5', 'slug' => 'mx-5'],
            ['car_brand_id' => 14, 'name' => 'MX-6', 'slug' => 'mx-6'],
            ['car_brand_id' => 14, 'name' => 'Premacy', 'slug' => 'premacy'],
            ['car_brand_id' => 14, 'name' => 'Protege', 'slug' => 'protege'],
            ['car_brand_id' => 14, 'name' => 'RX-6', 'slug' => 'rx-6'],
            ['car_brand_id' => 14, 'name' => 'RX-7', 'slug' => 'rx-7'],
            ['car_brand_id' => 14, 'name' => 'RX-8', 'slug' => 'rx-8'],
            ['car_brand_id' => 14, 'name' => 'Seria B', 'slug' => 'seria-b'],
            ['car_brand_id' => 14, 'name' => 'Seria E', 'slug' => 'seria-e'],
            ['car_brand_id' => 14, 'name' => 'Tribute', 'slug' => 'tribute'],
            ['car_brand_id' => 14, 'name' => 'Xedos', 'slug' => 'xedos'],
            ['car_brand_id' => 15, 'name' => '10', 'slug' => '10'],
            ['car_brand_id' => 15, 'name' => '11', 'slug' => '11'],
            ['car_brand_id' => 15, 'name' => '12', 'slug' => '12'],
            ['car_brand_id' => 15, 'name' => '14', 'slug' => '14'],
            ['car_brand_id' => 15, 'name' => '18', 'slug' => '18'],
            ['car_brand_id' => 15, 'name' => '19', 'slug' => '19'],
            ['car_brand_id' => 15, 'name' => '20', 'slug' => '20'],
            ['car_brand_id' => 15, 'name' => '21', 'slug' => '21'],
            ['car_brand_id' => 15, 'name' => '25', 'slug' => '25'],
            ['car_brand_id' => 15, 'name' => '30', 'slug' => '30'],
            ['car_brand_id' => 15, 'name' => '4', 'slug' => '4'],
            ['car_brand_id' => 15, 'name' => '5', 'slug' => '5'],
            ['car_brand_id' => 15, 'name' => '8', 'slug' => '8'],
            ['car_brand_id' => 15, 'name' => '9', 'slug' => '9'],
            ['car_brand_id' => 15, 'name' => 'Alaskan', 'slug' => 'alaskan'],
            ['car_brand_id' => 15, 'name' => 'Alpine A110', 'slug' => 'alpine-a110'],
            ['car_brand_id' => 15, 'name' => 'Alpine A310', 'slug' => 'alpine-a310'],
            ['car_brand_id' => 15, 'name' => 'Alpine V6', 'slug' => 'alpine-v6'],
            ['car_brand_id' => 15, 'name' => 'Arkana', 'slug' => 'arkana'],
            ['car_brand_id' => 15, 'name' => 'Austral', 'slug' => 'austral'],
            ['car_brand_id' => 15, 'name' => 'Avantime', 'slug' => 'avantime'],
            ['car_brand_id' => 15, 'name' => 'Captur', 'slug' => 'captur'],
            ['car_brand_id' => 15, 'name' => 'Clio', 'slug' => 'clio'],
            ['car_brand_id' => 15, 'name' => 'Coupe', 'slug' => 'coupe'],
            ['car_brand_id' => 15, 'name' => 'Espace', 'slug' => 'espace'],
            ['car_brand_id' => 15, 'name' => 'Express', 'slug' => 'express'],
            ['car_brand_id' => 15, 'name' => 'Fluence', 'slug' => 'fluence'],
            ['car_brand_id' => 15, 'name' => 'Fuego', 'slug' => 'fuego'],
            ['car_brand_id' => 15, 'name' => 'Grand Espace', 'slug' => 'grand-espace'],
            ['car_brand_id' => 15, 'name' => 'Grand Scenic', 'slug' => 'grand-scenic'],
            ['car_brand_id' => 15, 'name' => 'Inny', 'slug' => 'other'],
            ['car_brand_id' => 15, 'name' => 'Kadjar', 'slug' => 'kadjar'],
            ['car_brand_id' => 15, 'name' => 'Kangoo', 'slug' => 'kangoo'],
            ['car_brand_id' => 15, 'name' => 'Koleos', 'slug' => 'koleos'],
            ['car_brand_id' => 15, 'name' => 'Laguna', 'slug' => 'laguna'],
            ['car_brand_id' => 15, 'name' => 'Latitude', 'slug' => 'latitude'],
            ['car_brand_id' => 15, 'name' => 'Master', 'slug' => 'master'],
            ['car_brand_id' => 15, 'name' => 'Megane', 'slug' => 'megane'],
            ['car_brand_id' => 15, 'name' => 'Modus', 'slug' => 'modus'],
            ['car_brand_id' => 15, 'name' => 'Rafale', 'slug' => 'rafale'],
            ['car_brand_id' => 15, 'name' => 'Safrane', 'slug' => 'safrane'],
            ['car_brand_id' => 15, 'name' => 'Scenic', 'slug' => 'scenic'],
            ['car_brand_id' => 15, 'name' => 'Scenic Conquest', 'slug' => 'scenic-conquest'],
            ['car_brand_id' => 15, 'name' => 'Scenic RX4', 'slug' => 'scenic-rx4'],
            ['car_brand_id' => 15, 'name' => 'Symbioz', 'slug' => 'symbioz'],
            ['car_brand_id' => 15, 'name' => 'Talisman', 'slug' => 'talisman'],
            ['car_brand_id' => 15, 'name' => 'Thalia', 'slug' => 'thalia'],
            ['car_brand_id' => 15, 'name' => 'Trafic', 'slug' => 'trafic'],
            ['car_brand_id' => 15, 'name' => 'Twingo', 'slug' => 'twingo'],
            ['car_brand_id' => 15, 'name' => 'Twizy', 'slug' => 'twizy'],
            ['car_brand_id' => 15, 'name' => 'Vel Satis', 'slug' => 'vel-satis'],
            ['car_brand_id' => 15, 'name' => 'Wind', 'slug' => 'wind'],
            ['car_brand_id' => 15, 'name' => 'Zoe', 'slug' => 'zoe']
        ];

        foreach ($carModels as $model) {
            CarModel::create($model);
        }
    }
}
